-- MySQL Script generated by MySQL Workbench
-- Sun Oct  9 16:32:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema APS6
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema APS6
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `APS6` DEFAULT CHARACTER SET utf8 ;
USE `APS6` ;

-- -----------------------------------------------------
-- Table `APS6`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `APS6`.`usuario` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `biometria` LONGBLOB NOT NULL,
  `nome` VARCHAR(300) NOT NULL,
  `cargo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `username_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `APS6`.`regiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `APS6`.`regiao` (
  `idRegioes` INT NOT NULL AUTO_INCREMENT,
  `identificacao` VARCHAR(45) NULL,
  `impacto` VARCHAR(45) NULL,
  `ocorrencias` INT(6) NULL,
  PRIMARY KEY (`idRegioes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `APS6`.`propriedade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `APS6`.`propriedade` (
  `idpropriedades` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `num` VARCHAR(45) NOT NULL,
  `regiao` INT NOT NULL,
  PRIMARY KEY (`idpropriedades`),
  INDEX `fk_propriedades_Regioes1_idx` (`regiao` ASC),
  CONSTRAINT `fk_propriedades_Regioes1`
    FOREIGN KEY (`regiao`)
    REFERENCES `APS6`.`regiao` (`idRegioes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `APS6`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `APS6`.`responsavel` (
  `idResponsaveis` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `idade` INT NULL,
  `dataNasc` date null,
  `propriedade` INT NOT NULL,
  PRIMARY KEY (`idResponsaveis`, `propriedade`),
  INDEX `fk_Responsaveis_propriedades1_idx` (`propriedade` ASC),
  CONSTRAINT `fk_Responsaveis_propriedades1`
    FOREIGN KEY (`propriedade`)
    REFERENCES `APS6`.`propriedade` (`idpropriedades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use aps6;
insert into regiao (idRegioes, identificacao, impacto, ocorrencias) values (0,"Norte","",1);
insert into regiao (idRegioes, identificacao, impacto, ocorrencias) values (0,"Nordeste","",2);
insert into regiao (idRegioes, identificacao, impacto, ocorrencias) values (0,"Centro-Oeste","",3);
insert into regiao (idRegioes, identificacao, impacto, ocorrencias) values (0,"Sudeste","",4);
insert into regiao (idRegioes, identificacao, impacto, ocorrencias) values (0,"Sul","",5);

insert into usuario (iduser, login, biometria, nome, cargo) 
values (0,"vanderson","","Vanderson","Ministro da Natureza do Universo");
